# Generated by Django 3.2 on 2023-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='points',
            field=models.JSONField(verbose_name='points'),
        ),
    ]
