# Generated by Django 3.2 on 2023-03-26 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_points'),
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='locations',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='location.location'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(upload_to='content/media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('.mp4', '.png', '.jpg', '.jpeg', '.flv'))], verbose_name='media file'),
        ),
    ]
