# Generated by Django 3.2 on 2023-04-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_points'),
        ('content', '0003_auto_20230326_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='location.location'),
        ),
    ]
