# Generated by Django 3.2 on 2023-04-01 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_post_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(upload_to='content/media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'png', 'jpg', 'jpeg', 'flv'))], verbose_name='media file'),
        ),
    ]
